
GET http://127.0.0.1:8000/api/ticket/32/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5MTUxMjU4LCJpYXQiOjE3NTkwNjQ4NTgsImp0aSI6IjhlY2VlMGI1YTU3ODRkYWI4MjJhN2ZmMzQ2ODljNzk1IiwidXNlcl9pZCI6IjE3In0.Ym3t5qCwae_jLfzyp7k6vpcfNKriiVCpjUWJC4-6c8k
###

POST http://127.0.0.1:8000/api/ticket/

Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2OTQ4MTY3LCJpYXQiOjE3NTY4NjE3NjcsImp0aSI6Ijk5NzRlMmZlMDc2NjQyMzNiNjQ4YWIxNjAyNjFiMWQ0IiwidXNlcl9pZCI6IjExIn0.PGiaYf4MfW47C1uG7I1vwn1tWsUucwvothK1-M1p1ks

{
  "title": "BAD REQUEST",
  "description": "Lorsqu'un utilisateur tente de se connecter, une erreur 500 apparaît.",
  "priority": "haute"
}

###
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "username": "superuser",
    "password": "superuser"
}



###

POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
    "username": "CoolMan",
    "first_name": "Cool",
    "last_name": "Man",
    "email": "cool@gmaail.com",
    "password": "coolMan0",
    "confirmation": "coolMan0"
}

###

POST http://127.0.0.1:8000/api/auth/register/developer/
Content-Type: application/json

{
    "username": "Dev",
    "first_name": "Dev",
    "last_name": "Man",
    "email": "dev@gmail.com",
    "password": "developerMan0",
    "confirmation": "developerMan0"
}

###

GET http://127.0.0.1:8000/api/auth/me/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3Nzk2OTcwLCJpYXQiOjE3NTc3MTA1NzAsImp0aSI6IjJlZDllNmNhMGIyMjQ0ZTM4MDQ4MTVjY2UxMzJmNWZlIiwidXNlcl9pZCI6IjE3In0.VluKq044EkS0IFsqR0Hl2cJGyV06u56vO6OZ5x3La6U


###

GET http://127.0.0.1:8000/api/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3Nzk2OTcwLCJpYXQiOjE3NTc3MTA1NzAsImp0aSI6IjJlZDllNmNhMGIyMjQ0ZTM4MDQ4MTVjY2UxMzJmNWZlIiwidXNlcl9pZCI6IjE3In0.VluKq044EkS0IFsqR0Hl2cJGyV06u56vO6OZ5x3La6U

###

GET http://127.0.0.1:8000/api/tickets/user/14/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3Nzk2OTcwLCJpYXQiOjE3NTc3MTA1NzAsImp0aSI6IjJlZDllNmNhMGIyMjQ0ZTM4MDQ4MTVjY2UxMzJmNWZlIiwidXNlcl9pZCI6IjE3In0.VluKq044EkS0IFsqR0Hl2cJGyV06u56vO6OZ5x3La6U

###

PATCH   http://127.0.0.1:8000/api/ticket/20/accepted/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3Nzk2OTcwLCJpYXQiOjE3NTc3MTA1NzAsImp0aSI6IjJlZDllNmNhMGIyMjQ0ZTM4MDQ4MTVjY2UxMzJmNWZlIiwidXNlcl9pZCI6IjE3In0.VluKq044EkS0IFsqR0Hl2cJGyV06u56vO6OZ5x3La6U

###

GET http://127.0.0.1:8000/api/users/9/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5MDg3NzExLCJpYXQiOjE3NTkwMDEzMTEsImp0aSI6ImUwMzFkZDkyMjA3NDRiMGY5NzM5ODg4YjNkOGYwOWMyIiwidXNlcl9pZCI6IjE3In0.HnmvUnXBiSfx7V_auVnyW-5-EVhFMnFPVGTEPMWzRh4
