# Generated by Django 5.2.5 on 2025-08-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0007_alter_ticket_priority_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
