# Generated by Django 5.2.5 on 2025-08-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_remove_ticket_client_remove_user_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
    ]
