# Generated by Django 5.2.5 on 2025-08-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_user_is_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
