# Generated by Django 5.2.5 on 2025-08-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0007_alter_ticket_priority_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(default=False, verbose_name="Précise si l'utilisateur doit être considéré comme un développeur."),
        ),
    ]
