# Generated by Django 5.2.5 on 2025-08-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0008_delete_role_alter_user_is_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(default=False, help_text="Précise si l'utilisateur doit être considéré comme un développeur.", verbose_name='Développeur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='storage/profils/', verbose_name='Photo de profil'),
        ),
    ]
